'use client'
import { Provider } from "react-redux";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import { configureStore } from "@reduxjs/toolkit";
import UserReducer from "./UserReducer";
const inter = Inter({ subsets: ["latin"] });
const store=configureStore({
  reducer:{
    users:UserReducer
  }
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ClientLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
